export const GET_USERS = "GET_USERS";
export const GET_USER_POSTS = "GET_USER_POSTS";
export const GET_POST_DETAILS = "GET_POST_DETAILS";
export const GET_USER_ALBUMS = "GET_USER_ALBUMS";

export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USER_POSTS_ERROR = "GET_USER_POSTS_ERROR";
export const GET_POST_DETAILS_ERROR = "GET_POST_DETAILS_ERROR";
export const GET_USER_ALBUMS_ERROR = "GET_USER_ALBUMS_ERROR";
